spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: gypsyjr
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

#server:
#  servlet:
#    context-path: /admin
conf:
  sitesUrl:
    - http://www.playback.ru
    - https://www.skillbox.ru
  sitesName:
    - Плейбек.ру
    - Skillbox
  userAgent: Mozilla/5.0 (Windows NT 6.1; rv:98.0) Gecko/20100101 Firefox/98.0
  referrer: http://google.com