spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=True
    username: gypsyjr
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update


#server:
#  servlet:
#    context-path: /admin
conf:
  sitesUrl:
    - http://www.playback.ru
    - https://www.skillbox.ru
  sitesName:
    - Плейбек.ру
    - Skillbox
  userAgent: Mozilla/5.0 (Windows NT 6.1; rv:98.0) Gecko/20100101 Firefox/98.0
  referrer: http://google.com

#logging:
#  level:
#    org.springframework.web: trace
#    org.apache: trace